name: Build FragOS Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      profile:
        description: "Select build profile (e.g. plasma, xfce)"
        required: false
        default: "plasma"

jobs:
  build:
    name: Build FragOS
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Prepare profile config
      run: |
        mkdir -p rootfs/etc/
        cp profiles/${{ github.event.inputs.profile || 'plasma' }}/packages.conf packages.conf
        cp profiles/${{ github.event.inputs.profile || 'plasma' }}/services-to-enable.conf services-to-enable.conf
        cp profiles/${{ github.event.inputs.profile || 'plasma' }}/services-to-enable-user.conf services-to-enable-user.conf

    - name: Build Docker image
      run: docker build -t fragos-builder -f docker/Dockerfile .

    - name: Run FragOS build script inside Docker
      run: |
        docker run -u root --rm \
          -v ${{ github.workspace }}:/mnt \
          -e BUILD_USER=builder \
          -e OUTPUT_DIR=/mnt/output \
          fragos-builder \
          /mnt/scripts/build.sh github

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FragOS-${{ github.run_number }}.img.tar.xz
        path: output/*.img.tar.xz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: FragOS Release v${{ github.run_number }}
        tag_name: v${{ github.run_number }}
        files: output/*.img.tar.xz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
