name: System image build

permissions:
      contents: write
      packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build and publish docker container
    uses: ./.github/workflows/build-builder.yml

  build:
    needs:
     - build-docker-image
    name: Build FragOS UNSTABLE image
    uses: ./.github/workflows/build-system-image.yml
    with:
      postfix: "[UNSTABLE]"
